# -*- coding: utf-8 -*-

"""
openweatheronecallapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from openweatheronecallapi.api_helper import APIHelper


class CurrentTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(CurrentTests, cls).setUpClass()
        cls.controller = cls.client.current
        cls.response_catcher = cls.controller.http_call_back

    # Get the current weather info
    def test_current_weather_data(self):
        # Parameters for the API call
        lat = 37.8349
        lon = 122.1297
        exclude = 'hourly,minutely'
        units = 'imperial'
        lang = 'en'

        # Perform the API call through the SDK function
        result = self.controller.current_weather_data(lat, lon, exclude, units, lang)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


